//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int BatchId { get; set; }
        public int PDId { get; set; }
        public byte[] Batch1 { get; set; }
    
        public virtual ProDetail ProDetail { get; set; }
    }
}
