//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYear.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INVENTORY_SYSTEMEntities : DbContext
    {
        public INVENTORY_SYSTEMEntities()
            : base("name=INVENTORY_SYSTEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<ProDetail> ProDetails { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<purchaseledger> purchaseledgers { get; set; }
        public virtual DbSet<purchasesitem> purchasesitems { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<salesledger> salesledgers { get; set; }
        public virtual DbSet<Subcategory> Subcategories { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<userlog> userlogs { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<returneditem> returneditems { get; set; }
        public virtual DbSet<salesitem> salesitems { get; set; }
    }
}
