//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchasesitem
    {
        public int ID { get; set; }
        public int PurchaseId { get; set; }
        public Nullable<int> ProID { get; set; }
        public Nullable<int> PDId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        public virtual ProDetail ProDetail { get; set; }
        public virtual product product { get; set; }
        public virtual purchase purchase { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
