//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class returneditem
    {
        public string SalesID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProID { get; set; }
        public Nullable<int> PDId { get; set; }
        public int Quantity { get; set; }
        public decimal price { get; set; }
        public decimal Discount { get; set; }
        public decimal Total { get; set; }
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ProDetail ProDetail { get; set; }
        public virtual product product { get; set; }
        public virtual sale sale { get; set; }
    }
}
