//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sale()
        {
            this.returneditems = new HashSet<returneditem>();
            this.salesitems = new HashSet<salesitem>();
        }
    
        public int ID { get; set; }
        public string SalesId { get; set; }
        public string InvoiceId { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> CusID { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public decimal Discount { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<returneditem> returneditems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesitem> salesitems { get; set; }
        public virtual user user { get; set; }
    }
}
