//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYear.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SODetail
    {
        public int SODetail_Id { get; set; }
        public int SOID { get; set; }
        public int PDID { get; set; }
        [Required]
        public int S_Quantity { get; set; }
        [Required]
        public string BatchIdNo { get; set; }
        [Required]
        public decimal U_price { get; set; }
        [Required]
        public decimal Discount { get; set; }
        [Required]
        public decimal TotalPrice { get; set; }
    
        public virtual ProDetail ProDetail { get; set; }
        public virtual SalesOrderMaster SalesOrderMaster { get; set; }
    }
}
